apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-mczu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-mczu@sha256:a2924304c38c38b2ab39d8d0757f036738c2c9352de24d96acd60e542ee1bba7
        name: my-nodejs
        resources: {}
status: {}
